### ISSUE TITLE
Merge this with goodtables-py and rename goodtable-py asap

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionless-prototype-py#25]
As discussed previously we want to "take over" goodtables-py (and rename it) rather than starting anew. I think the sooner we do this the better to simplify matters and not have watching/starring/issues opening in happening 2 places.

## Acceptance

* [ ] We have one repo frictionless-py that has
  * [ ] Branch for old goodtables-py
  * [ ] Master is frictionless-py
* [ ] Notice in README about switching to goodtables-py branch if you want that

## Tasks

@roll this is just an idea - i'm sure you know better

* [ ] Branch master in goodtables-py into goodtables branch
* [ ] Merge this master into goodtables-py (easy as we forked off their to start with for this repo)
* [ ] Add notice to README
* [ ] Move all issues from this repo using "transfer issue" to goodtables repo
* [ ] Delete this repo (or rename)
* [ ] Rename goodtables-py to frictionless-py

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @rufuspollock,

Thanks, we will do ASAP when Lilly and I are fully back from next Monday (14th)

**Comment by roll** [comment]
I need to merge the branch I'm working on now and in a few days I'll be able to merge repos :+1: (cc @lwinfree)
