### ISSUE TITLE
Migrate SQL plugin

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-prototype-py#3]
# Overview

https://github.com/frictionlessdata/tableschema-sql-py

# Tasks

- [x] migrate the code
- [ ] connect the code
- [ ] write the guide
